beacon-biosignals/Legolas.jl

src/rows.jl
test/runtests.jl

With this PR, I get
```julia
julia> long_row
Row(Schema("bar@1"), (z = [0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], x = 1, y = 2))
```
where `long_row` is a row I added to the tests.
Without this tweak to the `show` method, I get:
```julia
julia> @test length(sprint(show, long_row; context = :limit => true)) < 200
Test Failed at REPL[13]:1
Expression: length(sprint(show, long_row; context = :limit => true)) < 200
Evaluated: 40142 < 200
ERROR: There was an error during testing
```
since it prints the whole matrix. With even bigger rows, I've had the 'ole ctrl-c -> segfault as it tries to convert the entire row into a string and the print it.

improve show method

---

Project.toml
docs/make.jl
docs/src/specification.md
src/rows.jl
test/runtests.jl

This will be relevant to reference in downstream specifications (e.g Onda)

include implementation-agnostic specification for Legolas tables

---

Project.toml
src/rows.jl
test/runtests.jl

alternative to https://github.com/beacon-biosignals/Legolas.jl/pull/13
#13 has admirable goals compared to this naive approach (e.g. parity between schema <-> Arrow layout) but I'd guess that the simplicity of just dumping whatever actual whole `fields` value we're given is probably better aligned with user expectations in practice

support Legolas.Row (de)serialization as an Arrow column element

---

examples/tour.jl

ref https://github.com/beacon-biosignals/Legolas.jl/issues/12#issuecomment-885982341
`Legolas.Row`s will sort input fields into an implementation-defined order, but compliance for any given schema does not require an order. So while the removed lines here are technically correct, they are kind of misleading

don't document any assumptions on `Row` field order

---

README.md

Updates README.md link to `tour.jl` to be branch agnostic. Currently the link is hard-coded to the `master` branch (which does not exist)

Updates `tour.jl` link be branch agnostic in README

---

.github/workflows/CI.yml

As mentioned in: https://github.com/codecov/codecov-action , codecov-action@v1 will be deprecated/sunset on February 1, 2022.
There are a few breaking changes mentioned in the codecov-action README.md, but I don't think this workflow uses any of the breaking changes mentioned.

Update to codecov-action v2

---

src/rows.jl

https://beacon-biosignals.github.io/Legolas.jl/dev/#Legolas.schema_qualified_string

Fix docstring formatting

---

src/rows.jl

In some Beacon-internal code, I'm using TOML as a serialization format for small tables. You can get UnknownSchemaErrors, which are then confusing if they tell you to `Arrow.Table` it.
Maybe this is one tiny step towards #34

tweak UnknownSchemaError language

---

docs/src/index.md
src/Legolas.jl
src/lift.jl
test/runtests.jl

Method ensure compatibility with types which do not define constructing instances of themselves. For example with `Time`:
```julia
julia> Time(Time(0))
ERROR: MethodError: no method matching Int64(::Time)
```
We can work around this with `Legolas.lift(x -> x isa Time ? x : Time(x), y)` but with this PR we can simply do `Legolas.lift_type(Time, y)`.

Add `construct` function

---

Project.toml

#40 introduces a change that is potentially breaking to existing code:  if MyPkg defines a schema extension like `"foo@1" > "bar@1"` and `bar@1` is defined in OtherPkg, but MyPkg does not ever do `using OtherPkg`, the `@row` macro is never run that defines the necessary `schema_qualified_string(::Schema{:bar,1})` method that's recursively called by `schema_qualified_string(::Schema{:foo,1})`.
This is, admittedly, a pretty weird state for a package to be in, but it has occurred "in the wild".  Because #40 introduces a `::Val{...}` that calls `schema_qualified_string`, that gets run at compile time and packages that would previously precompile without error now throw an error.  The error is informative (it says that teh schema defining code was probably not run, which is the case!) but it …

potentially breaking change introduced

---

src/rows.jl

Surly, `validate` throws an `ArgumentError` if `tables_schema` does **not** comply with `legolas_schema`?

missing "not" in docstring

---

src/schemas.jl
test/runtests.jl

Adds support for attaching docstrings to schema versions. I also attempted to also add support to `@schema` but it wasn't clear what construct the docstring should be attached to.
Fixes: #10

Support attaching docstrings to schema versions

---

Project.toml
docs/src/index.md
src/schemas.jl
test/runtests.jl

These are useful for building semi-generic functionality/harnesses atop suites of known `Legolas.SchemaVersion`s.
Note that this purposefully does NOT define/expose a function like  `schema_version_from_record_type(::Type{T<:AbstractRecord})::SchemaVersion` (though there is an underscore-prefixed function like this that Legolas needs for its own internal codegen usage). We do not intend on exposing this kind of function for reasons similar to those articulated [here](https://github.com/beacon-biosignals/Legolas.jl/pull/29#discussion_r771836108).

add `record_type` and `schema_version_from_record`

---

src/schemas.jl

Fixes an extremely unlikely case where a user would define a field with the same name we generate for the type parameters:
```julia
julia> using Legolas: Legolas, @schema, @version
julia> @schema "demo" Demo
julia> @version DemoV1 begin
x::(<:String)
_x_T::String
end
ERROR: syntax: function argument and static parameter names must be distinct around /Users/cvogt/.julia/dev/Legolas/src/schemas.jl:569
Stacktrace:
[1] top-level scope
@ none:1
[2] eval
@ ./boot.jl:368 [inlined]
[3] eval(x::Expr)
@ Base.MainInclude ./client.jl:478
[4] top-level scope
@ ~/.julia/dev/Legolas/src/schemas.jl:737
```

Use `gensym` for generated type parameters

---

src/schemas.jl

When creating the inner constructors for Legolas records we'd previously just duplicate most of the functionality of the constructors:
```julia
julia> using Legolas: Legolas, @schema, @version
julia> @schema "demo" Demo
julia> @version DemoV1 begin
a::(<:String) = coalesce(a, String('a':'z'))
b::Int64 = coalesce(b, typemax(Int64))
c::UInt64 = coalesce(c, typemax(UInt64))
d::Char = begin
d in ('a', 'b', 'c') ? d : throw(ArgumentError("Invalid d"))
end
end
julia> Legolas._generate_record_type_definitions(DemoV1SchemaVersion(), :DemoV1)
quote
#= /Users/cvogt/.julia/dev/Legolas/src/schemas.jl:568 =#
const DemoV1SchemaVersion = $(Expr(:quote, Legolas.SchemaVersion{:demo, 1}))
#= /Users/cvogt/.julia/dev/Legolas/src/schemas.jl:569 =#
struct DemoV1{_a_T <: String} <: (Legolas).AbstractRecord
#= …
```

Simplify non-parametric constructor on parameterized record types

---

Project.toml
examples/tour.jl
src/schemas.jl
test/runtests.jl

Fixes #44 but we'll probably want to spawn a new issue for https://github.com/beacon-biosignals/Legolas.jl/issues/44#issuecomment-1292609205. A quick example of this in action:
```julia
julia> using Legolas: Legolas, @schema, @version
julia> @schema "test.field-error" FieldError
julia> function _validate(x)
x in ("a", "b", "c") || throw(ArgumentError("Must be a, b, or c"))
return x
end
_validate (generic function with 1 method)
julia> @version FieldErrorV1 begin
a::Union{String,Missing} = Legolas.lift(_validate, a)
b::(<:Union{String,Missing}) = Legolas.lift(_validate, b)
c::Union{Integer,Missing}
d::(<:Union{Integer,Missing})
end
julia> FieldErrorV1(; a="invalid")
ERROR: ArgumentError: Invalid value set for field `a` ("invalid")
Stacktrace:
[1] FieldErrorV1(; a::String, b::Missing, …
```

Provide nice error messages when constructing record fields

---

examples/tour.jl
src/schemas.jl

Updates #85 to generate only `find_violations` methods. Additionally, `find_violations` also returns an empty array when no violations around found, the deprecation now provides guidance on how to update code, and I dropped `fast_fail` as this code isn't performance critical and if it is we may want to return a generator instead.

Use `find_violations` in `find_violation`

---

Project.toml
src/schemas.jl
test/runtests.jl

Fixes https://github.com/beacon-biosignals/Legolas.jl/issues/91
Here, my understanding is that whenever we are emitting `quote`'d code, we need to interpolate in `Legolas` (or other names) if we wish to refer to the package and not whatever name `Legolas` exists in the macro-caller's scope.

fix quoting issue

---

Project.toml
src/schemas.jl
test/runtests.jl

PR #89 fixed compatibility with Arrow v2.6 except when the schema field's declared type is e.g. `Union{Vector{T},Missing}` and what's passed for validation is some `AbstractVector`. This adds a method to `accepted_field_type` that recurses on the non-`Missing` type in a `Union` with `Missing`. Note that this also necessitated adding an explicit `accepted_field_type` method for `Any` to avoid infinite recursion with the fallback definition, since `(Union{T,Missing} where {T}) == Any`.

Add `accepted_field_type` for `Union`s with `Missing`

---

Project.toml
src/schemas.jl
test/runtests.jl

Currently, methods for `==`, `isequal`, `hash`, and `NamedTuple` are generated by the `@version` macro for every row type that gets defined. The bodies of these methods always follow the same patterns, none of which require any information that's only available in the context where the definitions are generated. In fact, specific methods don't need to be generated at all; `AbstractRecord`s can all use the same generic methods for these functions. This provides the following additional benefits:
- When many schema versions are defined, this significantly reduces the excessive number of redundant methods which make method autocompletion effectively useless.
- Defining the generic methods in terms of regular functions rather than generating expressions in the macro means that it's easier to …

Use common methods for Base functions instead of generating

---

src/schemas.jl
test/runtests.jl

The motivating use case for this was a set of schemas used as an enumeration of sorts, all of which inherit from a common parent but do not differ structurally from the parent.

Allow a schema version to declare no fields

---

docs/Project.toml

trivial change, but would error if we [lack docstrings](https://github.com/beacon-biosignals/Legolas.jl/pull/108#pullrequestreview-1793184479) in the future. E.g., deleting `is_valid_schema_name` from the docs locally to test:
```julia
julia> include("make.jl")
[ Info: SetupBuildDirectory: setting up build directory.
[ Info: Doctest: running doctests.
[ Info: ExpandTemplates: expanding markdown templates.
[ Info: CrossReferences: building cross-references.
[ Info: CheckDocument: running document checks.
┌ Error: 1 docstring not included in the manual:
│ 
│     Legolas.is_valid_schema_name :: Tuple{AbstractString}
│ 
│ These are docstrings in the checked modules (configured with the modules keyword)
│ that are not included in canonical @docs or @autodocs blocks.
└ @ Documenter …
```

bump documenter version

---

Project.toml
ext/LegolasConstructionBaseExt.jl
src/Legolas.jl
src/schemas.jl

The dependency on ConstructionBase serves to provide a few convenience methods for users of packages like Accessors; it doesn't provide any functionality used directly by Legolas. This makes it a perfect candidate for a package extension.
Package extensions are new in Julia 1.9, and Legolas currently supports Julia 1.6. That means that we can't fully remove ConstructionBase as a direct dependency yet, but we can restructure things to make that as easy as possible once we drop support for earlier Julia versions.

Move ConstructionBase dependency to an extension on 1.9+

---

Project.toml
docs/src/index.md
examples/tour.jl
ext/LegolasConstructionBaseExt.jl
src/Legolas.jl
src/constraints.jl
src/schemas.jl
test/runtests.jl

Adds basic constraint support for Legolas schemas so you can define constraints on the relationships between fields. Previously, this could be worked around by adding such logic into a field:
```julia
julia> using Legolas: @schema, @version
julia> @schema "old.constraint" OldConstraint
julia> @version OldConstraintV1 begin
a
b = begin
@assert a == b
b
end
end
julia> OldConstraintV1(; a=1, b=2)
ERROR: ArgumentError: Invalid value set for field `b` (2)
Stacktrace:
[1] OldConstraintV1(; a::Int64, b::Int64)
@ Main ~/.julia/dev/Legolas/src/schemas.jl:545
[2] top-level scope
@ REPL[4]:1
caused by: AssertionError: a == b
Stacktrace:
[1] macro expansion
@ ./REPL[3]:4 [inlined]
[2] OldConstraintV1(; a::Int64, b::Int64)
@ Main ~/.julia/dev/Legolas/src/schemas.jl:580
[3] top-level scope
@ REPL[4]:1 …
```

Add constraint support

---

src/constraints.jl

Based on actual use cases and examples in the tour, "follow" was meant, not "proceed"

fix @check docstring

---

src/schemas.jl

In 1.12, we'll be cleaning up and making consistent when world age increment happens. This package is currently relying on implicit world age increments that may go away in 1.12. See https://github.com/JuliaLang/julia/pull/56509. This PR adds appropriate annotations that the world age increment is required because the `_generate_*` invocations in the macro read the result of the previous eval. This PR strictly retains existing behavior. A potentially better solution may be to `invokelatest` the `_generate_*` functions, which would also allow this code to work at non-toplevel (which may nor may not be desirable).

Adjust to upcoming Julia 1.12 change in implicit world age increment
